Setting up API functionality
chelobotix/Leaderboard-Chelobotix pull request #2
Opened 2023-02-08 23:00 UTC by chelobotix

- In this PR, I fulfilled the following tasks:
- [x] Send and receive data from an API.
- [x] Create a new game using the API.
- [x] Implement the "Refresh" button that gets all scores for a game created.
- [x] Implement the form "Submit" button that saves a score for a game created.

2023-02-08 23:28 UTC, Felix45 requested changes
Hi @chelobotix, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif" />

## Highlights :heavy_check_mark: 
- [ ] No linter errors :white_check_mark: 
- [ ] Good descriptive commit messages :white_check_mark: 
- [ ] Descriptive pull request title and summary :white_check_mark: 
- [ ] Repository has a professional readme file :white_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 23:28 UTC, Felix45 commented on src/index.html
>            <input type="submit" value="Submit" />
- [ Required ] Please consider making the `submit button` work as expected, when the button is clicked it should `hit` the `POST` API endpoint and post user entries. Currently, when I click the button the page is refreshed and no new data is `fetched` from the `API` this shows that the new `entries` were not posted online. Please see the video below for more details on this.

- [ Required ] Please consider making the `refresh button` work as expected, when the button is clicked it should `hit` the `GET` API endpoint and fetch all the scores. Currently, when I click the button the list of scores on the page does not change.

## Video
https://user-images.githubusercontent.com/16392046/217673965-fb4e1958-d444-4232-a6f2-4752d236a02b.mp4

2023-02-09 13:58 UTC, chelobotix commented
All the observations have been fixed:

https://user-images.githubusercontent.com/65084923/217832240-1e2aaa20-b46e-4c36-aa34-e04bf9445842.mp4

2023-02-09 14:15 UTC, Tadesse-Alemayehu approved these changes
### Hi @chelobotix 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅
 - [ ]  Correct GitFlow. ✅
 - [ ]  Good commit history. ✅
 - [ ]  Good PR title/description. ✅
 - [ ]  All linters passed ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 14:15 UTC, Tadesse-Alemayehu commented on src/index.html
> +          <input type="text" name="score" placeholder="Your score" req />
- [Optional] Please make sure the type for the score is `number` to make sure all the data the user can enter is a number.

2023-02-09 14:28 UTC, merged